version: '3.9'

services:
  config-server:
    image: tiergesund-config-server:0.1
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3


  discovery-server:
    image: tiergesund-discovery-server:0.1
    container_name: discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    depends_on:
      - config-server
