openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /vets:
    get:
      summary: List of vets
      operationId: listVets
      tags:
        - vets
      responses:
        200:

  
